name: movie_ticket_booking_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  cupertino_icons: ^1.0.8